version: "2"
services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      # POSTGRES_PORT: ${DB_PORT}
    container_name: apicancha
    volumes:
      - ./postgres:/var/lib/postgresql/data
